package services

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
)

type AIEvaluation struct {
	Name            string  `json:"name"`
	ImpactDirection string  `json:"impactDirection"`
	Percentage      float64 `json:"percentage"`
}

type AIImpactAnalysis struct {
	Evaluations []AIEvaluation `json:"evaluations"`
}

var promptTemplate = `You are a savage, highly analytical financial algorithm operating a gamified university system where students are traded as volatile "stocks".
Your ONLY job is to analyze a community-verified piece of news about specific students and determine their precise individual impact on their stock prices based on Campus Culture dynamics.

REFERENCE GUIDELINES & VOLATILITY BENCHMARKS:
Remember to scale your impact precisely based on these examples (use them as strict baselines, not rules):

1. Academic & Research (The "Nerd" Metrics)
- Perfect GPA/Topping the batch: +10% to +15%
- Failing a major core subject: -10% to -15%
- Publishing a paper in a top-tier journal (e.g., IEEE): +15% to +20%
- Publishing in a minor/college magazine: +3% to +5%
- Getting caught cheating in an exam: -20% to -30% (High penalty)
- Winning a national-level hackathon: +15% to +20%
- Winning an intra-college hackathon: +5% to +8%
- Securing a prestigious academic scholarship: +10% to +15%
- Creating a highly utilized open-source tool for students: +8% to +12%
- Getting publicly praised by a strict professor: +4% to +7%

2. Career & Professional (The "Placement" Drivers)
- Landing a Tier-1/FAANG internship/PPO: +15% to +35%
- Landing a mid-level startup internship: +5% to +10%
- Getting fired/losing an internship due to bad performance: -15% to -25%
- Starting a successful, revenue-generating campus business: +15% to +20%
- Starting a scam/failed campus business: -10% to -20%
- Getting featured in external tech media: +20% to +25%
- Bagging a massive freelance client: +6% to +10%
- Getting rejected from a dream company (publicly known): -2% to -5%

3. Extracurricular & Leadership (The "Fame" Multipliers)
- Elected Student Council President: +20% to +30%
- Impeached/Removed from Student Council: -25% to -35%
- Organizing the main college cultural fest successfully: +12% to +18%
- Mismanaging or embezzling fest funds: -30% to -40% (Crash)
- Winning gold in an inter-college sports tournament: +10% to +15%
- Giving a TEDx or major guest talk: +10% to +15%
- Bringing a major celebrity/sponsor to campus: +15% to +20%

4. Social, Reputation & Personality (The "Gossip" Volatility)
- Going viral on campus meme pages (cool): +5% to +10%
- Going viral for cringe/embarrassing reasons: -8% to -15%
- Getting into a public physical altercation/fight: -15% to -25%
- Helping someone in a severe medical emergency: +12% to +18%
- Spreading fake news / Caught lying on resume: -20% to -30%
- Verified reports of being rude to mess workers/staff: -10% to -15%
- Notorious "free-rider" in group projects exposed: -8% to -12%

5. Dating & Bidding Module (The "Aura" Market)
- Forming a highly visible "Power Couple" with another top stock: +8% to +12%
- Exposed as cheating on a partner: -20% to -30%
- Going through a messy public breakup: -5% to -10%
- Revealing an impressive "Hidden Trait" post-purchase: +5% to +10%

News content: "%s"

Analyze the socio-economic friction generated by this news. Output ONLY valid JSON, returning an array of evaluated students identified in the text.
{
  "evaluations": [
    {
      "name": "<student name derived from the text>",
      "impactDirection": "POSITIVE" | "NEGATIVE" | "NEUTRAL",
      "percentage": <integer between 1 and 40 for this specific student>
    }
  ]
}`

func AnalyzeNewsImpact(newsContent string) (*AIImpactAnalysis, error) {
	apiKey := os.Getenv("GEMINI_API_KEY")
	if apiKey == "" || apiKey == "your_gemini_api_key_here" {
		// Mock logic if no API key is provided
		return &AIImpactAnalysis{Evaluations: []AIEvaluation{}}, fmt.Errorf("GEMINI_API_KEY is not set")
	}

	url := fmt.Sprintf("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=%s", apiKey)

	prompt := fmt.Sprintf(promptTemplate, strings.ReplaceAll(newsContent, "\"", "\\\""))

	requestBody, err := json.Marshal(map[string]interface{}{
		"contents": []interface{}{
			map[string]interface{}{
				"parts": []interface{}{
					map[string]interface{}{
						"text": prompt,
					},
				},
			},
		},
		"generationConfig": map[string]interface{}{
			"temperature":      0.1,
			"responseMimeType": "application/json",
		},
	})
	if err != nil {
		return nil, err
	}

	resp, err := http.Post(url, "application/json", bytes.NewBuffer(requestBody))
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("gemini api error: %s", string(body))
	}

	var geminiResp struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}

	if err := json.Unmarshal(body, &geminiResp); err != nil {
		return nil, fmt.Errorf("failed to parse gemini response wrapper: %v", err)
	}

	if len(geminiResp.Candidates) == 0 || len(geminiResp.Candidates[0].Content.Parts) == 0 {
		return nil, fmt.Errorf("empty response from gemini")
	}

	rawJSON := strings.TrimSpace(geminiResp.Candidates[0].Content.Parts[0].Text)
	rawJSON = strings.TrimPrefix(rawJSON, "```json")
	rawJSON = strings.TrimPrefix(rawJSON, "```")
	rawJSON = strings.TrimSuffix(rawJSON, "```")
	rawJSON = strings.TrimSpace(rawJSON)

	var analysis AIImpactAnalysis
	if err := json.Unmarshal([]byte(rawJSON), &analysis); err != nil {
		return nil, fmt.Errorf("failed to parse analysis JSON: %v. Raw string: %s", err, rawJSON)
	}

	return &analysis, nil
}
